language: python
python:
        - 3.5
        - 3.4
        - 2.7
        - nightly
        - pypy
        - pypy3
services:
        - docker
before_install:
        - docker run -d --publish=28015:28015 rethinkdb
install:
        - pip install . pytest
script:
        - py.test -v -s tests

